In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [4]:
# 2-d dimensional array;
np.array([[1,2,3,3],[5,4,3,2]])

array([[1, 2, 3, 3],
       [5, 4, 3, 2]])

In [8]:
# 3 dimensional array
np.array([[[1,2,3], [4,5,6]], [[7,8,9], [3,4,2]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 4, 2]]])

In [7]:
type(np.array([[[1,2,3], [4,5,6]], [[7,8,9], [3,4,2]]]))

numpy.ndarray

In [9]:
# array arange
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [12]:
# reshape = to change the 1 dimensional array to another array dimensional;
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# ndim = to know dimension of arrray

In [15]:
np.ndim(np.arange(1,13).reshape(3,4))

2

In [18]:
np.arange(100,120).reshape(2,10) # to make 2-D array;

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [21]:
np.ones((10, 10)) # generate 1 in 10*10

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
np.zeros((12, 15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
# to generate random values
np.random.random(10)

array([0.42943181, 0.92239575, 0.29475849, 0.36936389, 0.91778427,
       0.61835976, 0.7879191 , 0.34905453, 0.48621933, 0.50419781])

In [27]:
np.random.randint((10))

3

In [29]:
np.random.randint((10,10,10)) # it generate 0-10, 0-10, 0-10 any one number

array([7, 3, 7])

In [35]:
np.linspace(-10, 100, 10) # it will generate random 10 value from -10 to 100

array([-10.        ,   2.22222222,  14.44444444,  26.66666667,
        38.88888889,  51.11111111,  63.33333333,  75.55555556,
        87.77777778, 100.        ])

In [38]:
# it will generate 1 on the diagonal only.
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [43]:
a1 = np.arange(1,8)
a2 = np.array([[1,2,3,4], [3,9,2,8]])
a3 = np.arange(1,9).reshape(2,4)

In [44]:
a1

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
a2

array([[1, 2, 3, 4],
       [3, 9, 2, 8]])

In [46]:
a3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
a4 = np.arange(1,13).reshape(3,4)
a4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
np.ndim(np.array([[1,2,3,4], [3,9,2,8]]))

2

In [59]:
np.ndim(np.arange(10,70).reshape(2,3,10))

3

In [61]:
a4 = np.arange(10,70).reshape(2,3,10) # 3-dimensional array
a4

array([[[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]]])

In [62]:
np.arange(10,70).reshape(3,2,10) # 3-dimensional array
# no of array, row size, column size

array([[[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]]])

In [67]:
np.arange(10, 110).reshape(4,1,25)

array([[[ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,
          22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
          34]],

       [[ 35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,
          47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,
          59]],

       [[ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
          72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84]],

       [[ 85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
          97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
         109]]])

In [81]:
a1 =  np.arange(12).reshape(3,4)
a2  = np.arange(12,24).reshape(3,4)
a3  = np.arange(12,24).reshape(4,3)

In [73]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
# arithmetic operation
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [78]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [79]:
# relational operation
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [80]:
# vector operations: 
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [83]:
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [84]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [87]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [86]:
a2-a1

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [89]:
a1%a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# sin/tan/cos

In [91]:
np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [92]:
np.cos(a1)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ]])

In [93]:
np.tan(a3)

array([[-0.63585993,  0.46302113,  7.24460662],
       [-0.8559934 ,  0.30063224,  3.49391565],
       [-1.13731371,  0.15158947,  2.23716094],
       [-1.52749853,  0.00885166,  1.58815308]])

mean, median, 

In [94]:
np.mean(a2)

17.5

In [95]:
np.median(a2)

17.5

In [104]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
np.mod(a1, 2)

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [105]:
np.std(a1)

3.452052529534663

In [107]:
np.max(a1, axis=1) # one for column

array([ 3,  7, 11])

In [108]:
np.min(a2, axis=1)

array([12, 16, 20])

In [109]:
# use exponential form
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [111]:
# round 
np.random.random((2,3))

array([[0.56170354, 0.99666582, 0.85094001],
       [0.71269247, 0.86764646, 0.3812939 ]])

In [113]:
np.round(np.random.random((2,3))*100) # it will do round off.

array([[85., 11., 94.],
       [37., 34., 45.]])

In [114]:
np.floor(np.random.random((2,3))*100)

array([[68., 89., 17.],
       [29., 11.,  7.]])

In [115]:
np.ceil(np.random.random((2,3))*100)

array([[44., 88.,  1.],
       [79., 17., 84.]])

indexing and slicing

In [117]:
a1  = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [118]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [124]:
a2[1]

array([4, 5, 6, 7])

In [126]:
a2[-1]

array([ 8,  9, 10, 11])

In [125]:
a2[2,3]

11

In [123]:
a2[0,2]

2

In [127]:
a2[[1,1],[1,2]]

array([5, 6])

In [141]:
a2[[1,1],[1,2]] # this method hass not efficient.

array([5, 6, 5])

In [144]:
a2[1:3, 1:3] # this is efficient method

array([[ 5,  6],
       [ 9, 10]])

In [128]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
a2[:, 2]

array([ 2,  6, 10])

In [153]:
# 5 , 7
# 9, 11

a2[1:, 1::2]

array([[ 5,  7],
       [ 9, 11]])

In [158]:
a2[:3:2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [159]:
a2[1:2, ::2]

array([[4, 6]])

In [164]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [173]:
a2[0:3:3, -1::]

array([[3]])

In [177]:
a2[[0,2],[0,3]]

array([ 0, 11])

# fancing indexing

In [183]:
a2[[1,1,2,2],[1,3,1,3]]

array([ 5,  7,  9, 11])

In [184]:
a2[1::, [1,3]]

array([[ 5,  7],
       [ 9, 11]])

In [185]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [186]:
a2[[0,0,1,1],[0,2,1,3]]

array([0, 2, 5, 7])

# ravel, flattern

In [190]:
np.ravel(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# stacking

In [187]:
a2 = np.arange(12).reshape(3,4).
a3 = np.arange(12).reshape(3,4)

In [188]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [189]:
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

horizontal stack(hstack)

vstack

hsplit(a2,2)

vsplit(a2,3)